name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [melpa, load-file, byte-compile, checkdoc, package-lint]
    steps:
      - uses: actions/checkout@v2

      - uses: purcell/setup-emacs@master
        with:
          version: 27.2

      - uses: leotaku/elisp-check@master
        with:
          file: projectile-env.el
          check: ${{ matrix.check }}
          warnings_as_errors: true
